M48
; DRILL file {KiCad 9.0.0} date 2025-02-26T09:32:52-0400
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-02-26T09:32:52-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.150
%
G90
G05
T1
X178.8Y-111.6
T2
X178.8Y-104.4
M30
